### ISSUE TITLE
Another problematic type of recursion

### ISSUE THREAD

**Issue by danielnixon** [RebeccaStevens/is-immutable-type#98]
## Bug Report

The five turtles problem:

![image](https://user-images.githubusercontent.com/6418489/224683745-84e8a304-4f35-4c7a-9f66-d53980a1b964.png)

https://youtu.be/wpgKd-rwnMw?t=1714

```ts

type Foo<U> = {
  readonly a: U;
  readonly b: Foo<Foo<U>>;
};

type Bar<U> = {
  readonly a: U;
  readonly b: Bar<Bar<U>>;
};

declare const foo: Foo<string>;

const bar: Bar<string> = foo;
```

### Expected behavior

Linting terminates without error.

### Actual behavior

```
Oops! Something went wrong! :(

ESLint: 8.36.0

RangeError: Maximum call stack size exceeded
Occurred while linting /Users/danielnixon/dev/eslint-plugin-total-functions/src/rules/no-unsafe-mutable-readonly-assignment.test.ts:14
Rule: "functional/type-declaration-immutability"
    at pipelineEmitWithHintWorker (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:113722:44)
    at pipelineEmitWithHint (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:113716:17)
    at pipelineEmit (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:113656:13)
    at emit (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:113629:13)
    at emitListItemWithParenthesizerRuleSelector (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:117894:9)
    at emitNodeListItems (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:116613:17)
    at emitNodeList (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:116531:17)
    at emitList (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:116496:13)
    at emitTypeArguments (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:116436:13)
    at emitTypeReference (/Users/danielnixon/dev/eslint-plugin-total-functions/node_modules/typescript/lib/typescript.js:114538:13)
error Command failed with exit code 2.
```

### Steps to reproduce

Try to lint that five turtles example.

### Proposed changes

I think we have to stop arbitrarily after five (or seven?) turtles. I'm not sure what the state of the art is.

**Comment by danielnixon** [comment]
To explode `functional/type-declaration-immutability` it's enough to do:

```ts
type Foo<U> = {
  readonly b: Foo<Foo<U>>;
};
```

**Comment by danielnixon** [comment]
getRecursionIdentity and isDeeplyNestedType from checker.ts look like they hold the answer.
